dist: xenial
language: python
cache: pip
install:
- pip3 install poetry
- poetry install
matrix:
  include:
  - os: linux
    python: 3.7
    env: DEPLOY=yes
  - os: osx
    language: generic
addons:
  apt:
    packages:
      - libhidapi-hidraw0
      - libudev-dev
      - libusb-1.0-0-dev
      - libegl1-mesa
      - libx11-xcb1
services:
  - xvfb
script:
- bash scripts/test.sh
after_script:
- bash <(curl -s https://codecov.io/bash)
before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ];  then open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.15.pkg; fi
