name: Test Docs

on: 
  push:
    paths:
      - 'docs/*'
      - '.github/workflows/test-docs.yaml'
  pull_request:
    paths:
      - 'docs/*'
      - '.github/workflows/test-docs.yaml'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md'
          config: '.markdownlint.yml'
 
